minor refactoring for clarity

diff --git a/bin/kaleidoscope-builder b/bin/kaleidoscope-builder
--- a/bin/kaleidoscope-builder
+++ b/bin/kaleidoscope-builder
@@ -199,11 +199,11 @@ _find_sketch() {
 			return
 		fi
 	done
-	SKETCH_NOT_FOUND=1
-	if [ -n "${SKETCH_NOT_FOUND}" ]; then
-		echo "I couldn't find your sketch (.ino file)" >&2
-		exit 1
-	fi
+
+
+	# Didn't find a sketch
+	echo "I couldn't find your sketch (.ino file)" >&2
+	exit 1
 }
 
 _prompt_before_flashing() {
